"""Generate the three node-side scripts: bootstrap.sh, start.sh, stop.sh.

Conventions on the node (everything per-run, nothing shared between runs):

    ~/.saage_runs/<run_id>/
      saage/        engine source (rsynced from the laptop checkout)
      venv/         engine virtualenv
      flow/         the flow dir (flow.yaml + skills + helpers)
      ws/           workspace (cloned run branch / bundle, or fresh dir)
      ws.bundle     only in bundle mode
      run_env       per-run secrets, 0600, deleted when the run stops
      artifacts/    the "bucket": ledgers/results copied here by the sidecar;
                    `saage remote fetch` rsyncs this dir back
      status.json   {"phase": ..., "rc": ..., "updated": ...} heartbeat
      saage.log     engine output

The watchdog stops the RUN, never the box — v1 does not own machines.
"""
from __future__ import annotations

import shlex
from dataclasses import dataclass, field

# files the sidecar copies from ws/ into artifacts/ — the flows' ledgers and
# results, all of which are deliberately .gitignored (they can't travel via
# the run branch)
ARTIFACT_FILES = ("experiments.jsonl", "research_log.md", "eval_results.json",
                  "report.html", "report_narrative.md")


@dataclass
class RunSpec:
    run_id: str
    flow_file: str                      # filename inside flow/, e.g. "flow.yaml"
    ws_mode: str                        # 'ephemeral' | 'branch' | 'bundle'
    set_args: dict = field(default_factory=dict)     # --set k=v passthrough
    venv_arg: str | None = None                      # --venv passthrough
    sync_interval: int = 300
    max_run_days: float = 12.0

    @property
    def run_dir(self) -> str:           # as a remote shell expression
        return f"$HOME/.saage_runs/{self.run_id}"

    @property
    def session(self) -> str:
        return f"saage-{self.run_id}"


def _collect_fn() -> str:
    files = " ".join(ARTIFACT_FILES)
    return f"""collect() {{  # the artifacts/ dir is the run's "bucket"
  for f in {files}; do
    [ -f "ws/$f" ] && cp -f "ws/$f" artifacts/ 2>/dev/null
  done
  return 0
}}"""


def _status_fn() -> str:
    return """status() {
  printf '{"phase":"%s","rc":%s,"updated":"%s"}\\n' "$1" "${2:-0}" \\
         "$(date -u +%FT%TZ)" > status.json.tmp
  mv status.json.tmp status.json
}"""


def bootstrap_sh(spec: RunSpec) -> str:
    ws_setup = {
        "ephemeral": "mkdir -p ws",
        "branch": '[ -d ws/.git ] || git clone --quiet --branch "$WS_RUN_BRANCH" "$WS_REPO_URL" ws',
        "bundle": '[ -d ws/.git ] || git clone --quiet --branch "$WS_RUN_BRANCH" ./ws.bundle ws',
    }[spec.ws_mode]
    return f"""#!/usr/bin/env bash
# generated by saage remote handoff — run {spec.run_id}
set -euo pipefail
export PATH="$HOME/.local/bin:$PATH"
cd "{spec.run_dir}"
set -a; source ./run_env; set +a

command -v uv >/dev/null 2>&1 || curl -LsSf https://astral.sh/uv/install.sh | sh
export PATH="$HOME/.local/bin:$PATH"

uv venv venv --quiet
VIRTUAL_ENV="$PWD/venv" uv pip install --quiet -e ./saage

mkdir -p artifacts
{ws_setup}
echo BOOTSTRAP_OK
"""


def start_sh(spec: RunSpec) -> str:
    set_flags = " ".join(
        f"--set {shlex.quote(f'{k}={v}')}" for k, v in spec.set_args.items()
    )
    venv_flag = f"--venv {shlex.quote(spec.venv_arg)}" if spec.venv_arg else ""
    max_run_seconds = int(spec.max_run_days * 86400)
    return f"""#!/usr/bin/env bash
# generated by saage remote handoff — run {spec.run_id}
set -uo pipefail
export PATH="$HOME/.local/bin:$PATH"
cd "{spec.run_dir}"
set -a; source ./run_env; set +a

{_status_fn()}

{_collect_fn()}

( while true; do status running; collect; sleep {spec.sync_interval}; done ) &
SIDECAR=$!
# watchdog: a wedged run can't hold the box forever — stops the RUN, never the box
( sleep {max_run_seconds} && touch watchdog_fired && pkill -P $$ 2>/dev/null ) &
WATCHDOG=$!

status running
venv/bin/saage run "flow/{spec.flow_file}" --workspace "$PWD/ws" {venv_flag} {set_flags} \\
  > saage.log 2>&1
RC=$?

kill "$SIDECAR" "$WATCHDOG" 2>/dev/null
collect
# push kept experiments out, when the workspace has a pushable origin
( cd ws && git push -q origin "${{WS_RUN_BRANCH:-}}" 2>/dev/null ) || true
if [ -f watchdog_fired ]; then status timeout 124
elif [ "$RC" -eq 0 ]; then status done 0
else status failed "$RC"; fi
rm -f run_env            # secrets do not outlive the run
"""


def stop_sh(spec: RunSpec) -> str:
    files = " ".join(ARTIFACT_FILES)
    return f"""#!/usr/bin/env bash
# generated by saage remote handoff — run {spec.run_id}
# stop the RUN, never the box
cd "{spec.run_dir}" || exit 0
tmux kill-session -t {shlex.quote(spec.session)} 2>/dev/null || true
mkdir -p artifacts
for f in {files}; do
  [ -f "ws/$f" ] && cp -f "ws/$f" artifacts/ 2>/dev/null
done
printf '{{"phase":"killed","rc":137,"updated":"%s"}}\\n' "$(date -u +%FT%TZ)" > status.json
rm -f run_env
exit 0
"""
